<a href="https://colab.research.google.com/github/yinzhuo-github/python_study/blob/Numpy/numpy%E7%9A%84%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 创建一个数组,类型为<class 'numpy.ndarray'>, array.reshape()

arr_1D = np.arange(12) # 生成一个一维的 ndarray
print("一维：","\n",arr_1D)
arr_2D = arr_1D.reshape((4, 3))  # reshape后, 转换成一个二维的 ndarray
print("二维：","\n",arr_2D)
arr_3D = arr_1D.reshape(2,3,2)   # reshape后, 转换成一个三维的 ndarray，这个(2,3,2)的含义还没搞懂！！
print("三维：","\n",arr_3D)

一维： 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
二维： 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
三维： 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
# 转置transpose, array.T
arr_transpose = arr_2D.T
print("转置后：", "\n", arr_transpose)

转置后： 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
# 矩阵点积, np.dot()
arr_dot_product = np.dot(arr_2D, arr_transpose)
print("矩阵的点积为：", "\n", arr_dot_product)

矩阵的点积为： 
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [ ]:
# 查询矩阵信息
print(f"Shape of arr_3D: {arr_3D.shape}")
print(f"Size of arr_3D: {arr_3D.size}")
print(f"Type of arr_3D: {arr_3D.dtype}")

Shape of arr_3D: (2, 3, 2)
Size of arr_3D: 12
Type of arr_3D: int64


In [ ]:
# 创建一个内部等距的矩阵， np.linspace()
arr3 = np.linspace(2,10,6) #间隔即为：(10-2)/5
print(arr3)
arr4 = arr3.reshape(2,-1) # -1为占位，numpy可以推测后面的值
print(arr4)

[ 2.   3.6  5.2  6.8  8.4 10. ]
[[ 2.   3.6  5.2]
 [ 6.8  8.4 10. ]]


In [ ]:
arr_eye1 = np.eye(3)
print("eye(3):" ,"\n")
print(arr_eye1,"\n"*2)

arr_identity1 = np.identity(3)
print("identity(3):" ,"\n")
print(arr_identity1,"\n"*2)

arr_eye2 = np.eye(5)
print("eye(5):" ,"\n")
print(arr_eye2,"\n"*2)

arr_identity2 = np.identity(5)
print("identity(5):" ,"\n")
print(arr_identity2,"\n"*2)

eye(3): 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 


identity(3): 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 


eye(5): 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 


identity(5): 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 


